// category_dto.go - generated by api:generate category


package dto

import (
	"jk-api/internal/database/models"
)

// CreateCategoryDto is used when creating a new Category.
type CreateCategoryDto struct {
	Code             string `json:"code"`
	Name             string `json:"name"`
}

// UpdateCategoryDto is used when updating an existing Category.
type UpdateCategoryDto struct {
	Code             *string `json:"code"`
	Name             *string `json:"name"`
}

// CategoryResponseDto represents a detailed view of Category with related data.
type CategoryResponseDto struct {
	models.Category
}