// project_dto.go - generated by api:generate project

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreateProjectDto is used when creating a new Project.
type CreateProjectDto struct {
	Nama string `json:"nama"`
	Kode string `json:"kode"`
}

// UpdateProjectDto is used when updating an existing Project.
type UpdateProjectDto struct {
	Nama      *string    `json:"nama"`
	Kode      *string    `json:"kode"`
	Deskripsi *string    `json:"deskripsi"`
	StartDate *time.Time `json:"start_date"`
	EndDate   *time.Time `json:"end_date"`
}

// ProjectResponseDto represents a detailed view of Project with related data.
type ProjectResponseDto struct {
	models.Project
}
