// squad_dto.go - generated by api:generate squad

package dto

import (
	"jk-api/internal/database/models"
)

// CreateSquadDto is used when creating a new Squad.
type CreateSquadDto struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ProjectID   *int64  `json:"project_id"`
}

// UpdateSquadDto is used when updating an existing Squad.
type UpdateSquadDto struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Captain     *int64  `json:"captain"`
	ProjectID   *int64  `json:"project_id"`
}

// SquadResponseDto represents a detailed view of Squad with related data.
type SquadResponseDto struct {
	models.Squad
}
