// squad_dto.go - generated by api:generate squad

package dto

import (
	"jk-api/internal/database/models"
)

// CreateSquadDto is used when creating a new Squad.
type CreateSquadDto struct {
	Name string `json:"name"`
}

// UpdateSquadDto is used when updating an existing Squad.
type UpdateSquadDto struct {
	Name *string `json:"name"`
}

// SquadResponseDto represents a detailed view of Squad with related data.
type SquadResponseDto struct {
	models.Squad
}
