// user_dto.go - generated by api:generate user

package dto

import (
	"jk-api/internal/database/models"
)

// CreateUserDto is used when creating a new User.
type CreateUserDto struct {
	Nama  string `json:"nama"`
	Email string `json:"email"`
}

// UpdateUserDto is used when updating an existing User.
type UpdateUserDto struct {
	Nama  *string `json:"nama"`
	Email *string `json:"email"`
}

// UserResponseDto represents a detailed view of User with related data.
type UserResponseDto struct {
	models.User
}
