// squad_controller.go - generated by api:generate squad


package controllers

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/api/controllers/v1/handlers"
	"jk-api/api/presenters"
	"jk-api/pkg/services/v1"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

var SquadService services.SquadService

func GetSquads(c *fiber.Ctx) error {
	data, err := handlers.GetAllSquadsHandler()
	if err != nil {
		return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
	}
	return presenters.SuccessResponse(c, data)
}

func GetSquadByID(c *fiber.Ctx) error {
	id, err := strconv.ParseInt(c.Params("id"), 10, 64)
	if err != nil {
		return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
	}

	data, err := handlers.GetSquadByIDHandler(id)
	if err != nil {
		return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
	}
	return presenters.SuccessResponse(c, data)
}

func CreateSquads(c *fiber.Ctx) error {
	var input dto.CreateSquadDto
	if err := c.BodyParser(&input); err != nil {
		return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
	}

	result, err := handlers.CreateSquadHandler(&input)
	if err != nil {
		return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
	}
	return presenters.SuccessResponse(c, result)
}

func UpdateSquads(c *fiber.Ctx) error {
	id, err := strconv.ParseInt(c.Params("id"), 10, 64)
	if err != nil {
		return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
	}

	var input dto.UpdateSquadDto
	if err := c.BodyParser(&input); err != nil {
		return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
	}

	updated, err := handlers.UpdateSquadHandler(id, &input)
	if err != nil {
		return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
	}
	return presenters.SuccessResponse(c, updated)
}

func DeleteSquads(c *fiber.Ctx) error {
	id, err := strconv.ParseInt(c.Params("id"), 10, 64)
	if err != nil {
		return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
	}

	if err := handlers.DeleteSquadHandler(id); err != nil {
		return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
	}
	return presenters.SuccessResponseWithMessage(c, "Squad deleted successfully", nil)
}
	