// category_container.go - generated by api:generate category

package container

import (
	"jk-api/api/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitCategoryContainer() *handlers.CategoryHandler {
	repo := sql.NewCategoryRepository()
	service := services.NewCategoryService(repo)
	return handlers.NewCategoryHandler(service)
}
