// project_container.go - generated by api:generate project

package container

import (
	"jk-api/api/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitProjectContainer() *handlers.ProjectHandler {
	repo := sql.NewProjectRepository()
	service := services.NewProjectService(repo)
	return handlers.NewProjectHandler(service)
}
