// squad_container.go - generated by api:generate squad

package container

import (
	"jk-api/api/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitSquadContainer() *handlers.SquadHandler {
	repo := sql.NewSquadRepository()
	service := services.NewSquadService(repo)

	projectSquadRepo := sql.NewProjectSquadRepository()
	projectSquadService := services.NewProjectSquadService(projectSquadRepo)

	return handlers.NewSquadHandler(service, projectSquadService)
}
