// user_container.go - generated by api:generate user

package container

import (
	"jk-api/api/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitUserContainer() *handlers.UserHandler {
	repo := sql.NewUserRepository()
	service := services.NewUserService(repo)
	return handlers.NewUserHandler(service)
}
