// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Judul      string    `gorm:"column:judul;not null" json:"judul"`
	Deskripsi  string    `gorm:"column:deskripsi" json:"deskripsi"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	Prioritas  string    `gorm:"column:prioritas" json:"prioritas"`
	AssignedTo int32     `gorm:"column:assigned_to" json:"assigned_to"`
	// ProjectID  int32     `gorm:"column:project_id" json:"project_id"`
	DueDate    time.Time `gorm:"column:due_date" json:"due_date"`
	CreatedBy  int32     `gorm:"column:created_by" json:"created_by"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
