// category_dto.go - generated by api:generate category

package mapper

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateCategoryDtoToModel(dto *dto.CreateCategoryDto) (*models.Category, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Category{
		Code: dto.Code,
		Name: dto.Name,
	}

	return data, nil
}

func UpdateCategoryDtoToModel(dto *dto.UpdateCategoryDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Code != nil {
		updates["code"] = *dto.Code
	}
	if dto.Name != nil {
		updates["name"] = *dto.Name
	}

	return updates, nil
}


func CategoryModelToResponseDto(data *models.Category) (*dto.CategoryResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.CategoryResponseDto{
		Category: *data,
	}

	return responseDto, nil
}