// project_dto.go - generated by api:generate project

package mapper

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateProjectDtoToModel(dto *dto.CreateProjectDto) (*models.Project, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Project{
		Nama: dto.Nama,
		Kode: dto.Kode,
	}

	return data, nil
}

func UpdateProjectDtoToModel(dto *dto.UpdateProjectDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Nama != nil {
		updates["nama"] = *dto.Nama
	}
	if dto.Kode != nil {
		updates["kode"] = *dto.Nama
	}
	if dto.Deskripsi != nil {
		updates["deskripsi"] = *dto.Deskripsi
	}
	if dto.StartDate != nil {
		updates["start_date"] = *dto.StartDate
	}
	if dto.EndDate != nil {
		updates["end_date"] = *dto.EndDate
	}

	return updates, nil
}

func ProjectModelToResponseDto(data *models.Project) (*dto.ProjectResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.ProjectResponseDto{
		Project: *data,
	}

	return responseDto, nil
}
