// squad_dto.go - generated by api:generate squad

package mapper

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateSquadDtoToModel(dto *dto.CreateSquadDto) (*models.Squad, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Squad{
		Name: dto.Name,
	}

	return data, nil
}

func SquadModelToResponseDto(data *models.Squad) (*dto.SquadResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.SquadResponseDto{
		Squad: *data,
	}

	return responseDto, nil
}
