// squad_dto.go - generated by api:generate squad

package mapper

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateSquadDtoToModel(dto *dto.CreateSquadDto) (*models.Squad, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Squad{
		Name: dto.Name,
	}

	return data, nil
}

func UpdateSquadDtoToModel(dto *dto.UpdateSquadDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Name != nil {
		updates["name"] = *dto.Name
	}
	if dto.Description != nil {
		updates["description"] = *dto.Description
	}
	if dto.Captain != nil {
		updates["captain"] = *dto.Captain
	}

	return updates, nil
}

func SquadModelToResponseDto(data *models.Squad) (*dto.SquadResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.SquadResponseDto{
		Squad: *data,
	}

	return responseDto, nil
}
