// category_handler.go - generated by api:generate category


package handlers

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/api/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

type CategoryHandler struct {
	Service services.CategoryService
}

func NewCategoryHandler(service services.CategoryService) *CategoryHandler {
	return &CategoryHandler{Service: service}
}

func (h *CategoryHandler) CreateCategoryHandler(input *dto.CreateCategoryDto) (*dto.CategoryResponseDto, error) {
	db := h.Service.GetDB().Begin()
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
		}
	}()

	categoryService := h.Service.WithTx(db)

	newData, err := mapper.CreateCategoryDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := categoryService.CreateCategory(newData)
	if err != nil {
		db.Rollback()
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}

	return mapper.CategoryModelToResponseDto(createdData)
}

func (h *CategoryHandler) UpdateCategoryHandler(id int64, input *dto.UpdateCategoryDto) (*models.Category, error) {
	db := h.Service.GetDB().Begin()
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
		}
	}()

	categoryService := h.Service.WithTx(db)

	payload, err := mapper.UpdateCategoryDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := categoryService.UpdateCategory(id, payload)
	if err != nil {
		db.Rollback()
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}

	return updatedData, nil
}

func (h *CategoryHandler) DeleteCategoryHandler(id int64) error {
	return h.Service.DeleteCategory(id)
}

func (h *CategoryHandler) GetCategoryByIDHandler(id int64) (*models.Category, error) {
	return h.Service.GetCategoryByID(id)
}

func (h *CategoryHandler) GetAllCategorysHandler() ([]models.Category, error) {
	return h.Service.GetAllCategorys()
}