// squad_handler.go - generated by api:generate squad

// squad_handler.go - generated by api:generate squad

package handlers

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

var SquadService services.SquadService

func CreateSquadHandler(input *dto.CreateSquadDto) (*models.Squad, error) {
	newSquad := &models.Squad{
		Name: input.Name,
	}

	return SquadService.CreateSquad(newSquad)
}

func UpdateSquadHandler(id int64, input *dto.UpdateSquadDto) (*models.Squad, error) {
	updateData := &models.Squad{}
	if input.Name != nil {
		updateData.Name = *input.Name
	}

	return SquadService.UpdateSquad(id, updateData)
}

func DeleteSquadHandler(id int64) error {
	return SquadService.DeleteSquad(id)
}

func GetSquadByIDHandler(id int64) (*models.Squad, error) {
	return SquadService.GetSquadByID(id)
}

func GetAllSquadsHandler() ([]models.Squad, error) {
	return SquadService.GetAllSquads()
}
