// user_handler.go - generated by api:generate user

package handlers

import (
	"fmt"
	"jk-api/api/controllers/v1/dto"
	"jk-api/api/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

type UserHandler struct {
	Service services.UserService
}

func NewUserHandler(service services.UserService) *UserHandler {
	return &UserHandler{Service: service}
}

func (h *UserHandler) CreateUserHandler(input *dto.CreateUserDto) (*dto.UserResponseDto, error) {
	db := h.Service.GetDB().Begin()
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
		}
	}()

	userService := h.Service.WithTx(db)

	newData, err := mapper.CreateUserDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := userService.CreateUser(newData)
	if err != nil {
		db.Rollback()
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}

	return mapper.UserModelToResponseDto(createdData)
}

func (h *UserHandler) UpdateUserHandler(id int64, input *dto.UpdateUserDto) (*models.User, error) {
	// TODO: Assign fields from input to updateData
	db := h.Service.GetDB().Begin()
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
		}
	}()

	userService := h.Service.WithTx(db)

	payload, err := mapper.UpdateUserDtoToModel(input)
	fmt.Println(payload)
	if err != nil {
		db.Rollback()
		return nil, err
	}

	updatedData, err := userService.UpdateUser(id, payload)
	if err != nil {
		db.Rollback()
		return nil, err
	}

	db.Commit()
	return updatedData, nil
}

func (h *UserHandler) DeleteUserHandler(id int64) error {
	return h.Service.DeleteUser(id)
}

func (h *UserHandler) GetUserByIDHandler(id int64) (*models.User, error) {
	return h.Service.GetUserByID(id)
}

func (h *UserHandler) GetAllUsersHandler() ([]models.User, error) {
	return h.Service.GetAllUsers()
}
