// category_routes.go - generated by api:generate category


package routes

import (
	"jk-api/api/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func CategoryRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("categories")

	app.Get("/", controllers.GetCategorys(c))
	app.Post("/", controllers.CreateCategorys(c))
	app.Put("/:id", controllers.UpdateCategorys(c))
	app.Delete("/:id", controllers.DeleteCategorys(c))
}
