// project_routes.go - generated by api:generate project


package routes

import (
	"jk-api/api/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func ProjectRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("projects")

	app.Get("/", controllers.GetProjects(c))
	app.Post("/", controllers.CreateProjects(c))
	app.Put("/:id", controllers.UpdateProjects(c))
	app.Delete("/:id", controllers.DeleteProjects(c))
}
