// squad_routes.go - generated by api:generate squad

package routes

import (
	"jk-api/api/controllers/v1"

	"github.com/gofiber/fiber/v2"
)

func SquadRoutes(router fiber.Router) {
	app := router.Group("squads")

	app.Get("/", controllers.GetSquads)
	app.Post("/", controllers.CreateSquads)
	app.Put("/:id", controllers.UpdateSquads)
	app.Delete("/:id", controllers.DeleteSquads)
}
