// squad_routes.go - generated by api:generate squad

package routes

import (
	"jk-api/api/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func SquadRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("squads")

	app.Get("/", controllers.GetSquads(c))
	app.Post("/", controllers.CreateSquads(c))
	app.Put("/:id", controllers.UpdateSquads(c))
	app.Delete("/:id", controllers.DeleteSquads(c))
}
