// user_routes.go - generated by api:generate user


package routes

import (
	"jk-api/api/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func UserRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("Users")

	app.Get("/", controllers.GetUsers(c))
	app.Post("/", controllers.CreateUsers(c))
	app.Put("/:id", controllers.UpdateUsers(c))
	app.Delete("/:id", controllers.DeleteUsers(c))
}
